### ISSUE TITLE
go install github.com/go-micro/dashboard@latest failed, sematic version tags needed

### ISSUE THREAD

**Issue by morya** [go-micro/dashboard#13]
running with this command copied from README doc.

```shell
go install github.com/go-micro/dashboard@latest
```

output like this

```
go: downloading github.com/go-micro/dashboard v1.0.0
go install: github.com/go-micro/dashboard@latest: github.com/go-micro/dashboard@v1.0.0: parsing go.mod:
	module declares its path as: github.com/xpunch/go-micro-dashboard
	        but was required as: github.com/go-micro/dashboard
```

IMHO, I think it should have a tag `v1.4.1`, tag `1.4.1` not working

**Comment by xpunch** [comment]
Thanks for your notice, v1.4.1 has been created.
I've created 1.4.1 for docker image tags, which do not need prefix v, but I forgot about the go mod semantic  versioning rules.
