### ISSUE TITLE
Registry consul not found

### ISSUE THREAD

**Issue by JellyZero** [go-micro/dashboard#18]

**Comment by xpunch** [comment]
All plugins were moved into https://github.com/go-micro/plugins.

**Comment by JellyZero** [comment]
dashboard 启动报错 Registry consul not found

**Comment by JellyZero** [comment]
go run main.go --registry=consul --registry_address=127.0.0.1:8500

**Comment by xpunch** [comment]
try
```
go run . --registry consul
```
